/*
 * Laser Step Test - This example demonstrates laser patterns generated by the
   laser beam reflected from two mirrors mounted on two DC motors. 
   
 * Author : Electronut Labs
 * Website  : electronut.in
*/

// DRV8835 initializations.
int AIN1 = A5;
int AIN2 = 9;
int BIN1 = A4;
int BIN2 = 8;
int MODE = 7;

// RGB LED initializations.
int R = 12;
int G = 11;
int B = 13;

void setup()
{
  pinMode(AIN1, OUTPUT);
  pinMode(AIN2, OUTPUT);
  pinMode(BIN1, OUTPUT);
  pinMode(BIN2, OUTPUT);
  pinMode(MODE, OUTPUT);

  // set up DRV8835 in PH/EN mode.
  digitalWrite(MODE, HIGH);

  // set up motors to spin in opposite directions.
  digitalWrite(AIN1, HIGH);
  analogWrite(AIN2, 50);
  digitalWrite(BIN1, LOW);
  analogWrite(BIN2, 75);

  // RGB LED
  pinMode(R, OUTPUT);
  pinMode(G, OUTPUT);
  pinMode(B, OUTPUT);
  // turn RGB LED off.
  digitalWrite(R, HIGH);
  digitalWrite(G, HIGH);
  digitalWrite(B, HIGH);

  // red ON
  digitalWrite(R, LOW);
  digitalWrite(G, HIGH);
  digitalWrite(B, HIGH);

  delay(1000);

  // LED OFF
  digitalWrite(R, HIGH);
  digitalWrite(G, HIGH);
  digitalWrite(B, HIGH);

  delay(1000);

  // red ON
  digitalWrite(R, LOW);
  digitalWrite(G, HIGH);
  digitalWrite(B, HIGH);

  delay(1000);

  // LED OFF
  digitalWrite(R, HIGH);
  digitalWrite(G, HIGH);
  digitalWrite(B, HIGH);

  delay(1000);
}

void loop()
{
  // random value generated lies between 0 and 255 due to 8-bit PWM
  int val1 = random(0, 255);
  if (val1 > 128) {
    digitalWrite(AIN1, HIGH);
    digitalWrite(BIN1, LOW);
    // cyan
    digitalWrite(R, HIGH);
    digitalWrite(G, LOW);
    digitalWrite(B, LOW);
  }
  else {
    digitalWrite(AIN1, LOW);
    digitalWrite(BIN1, HIGH);

    // magenta
    digitalWrite(R, LOW);
    digitalWrite(G, HIGH);
    digitalWrite(B, LOW);
  }

  int val2 = random(50, 150);
  int val3 = random(50, 150);

  analogWrite(AIN2, val2);
  analogWrite(BIN2, val3);

  // run motors at same speed for 5 seconds.
  delay(5000);
}
